### ISSUE TITLE
Use DTOs

### ISSUE THREAD

**Issue by DannySS123** [kir-dev/programSCH#15]
Some DTO-s are defined, but not used anywhere (e.g. UpdateUserDto, CreateEventDto, etc.).
Either use them or remove them if they are not necessary.

**Comment by justnyx** [comment]
![Screenshot 2024-05-27 190257](https://github.com/kir-dev/programSCH/assets/107306194/9d149b77-d785-462e-a966-e17b423f0332)

i need some help with this @DannySS123

**Comment by DannySS123** [comment]
@justnyx oh, I forgot to mention that this issue is dependent on the other one: https://github.com/kir-dev/programSCH/issues/16
since we don't want to pass e.g. the users to an event as a field, but rather use the prisma connect to create the relations in the db. It looks something like this, but feel free tocheck it In the prisma [docs](https://www.prisma.io/docs/orm/prisma-client/queries/relation-queries#connect-multiple-records)
![image](https://github.com/kir-dev/programSCH/assets/65909866/8ec65bd3-bd81-429a-a0fb-d00987ec58c7)

**Comment by justnyx** [comment]
Does this mean I need to pass the authSchId as a parameter for the create function? @DannySS123

**Comment by DannySS123** [comment]
@justnyx Nope, this is just an example, but we usually connect with ID-s

**Comment by SzBeni2003** [comment]
![kép](https://github.com/kir-dev/programSCH/assets/58933758/59655981-6a4c-43f2-9800-5de503c5226f)
![Képernyőkép 2024-07-05 012952](https://github.com/kir-dev/programSCH/assets/58933758/c68da75c-6e07-4ca6-9584-8f0fa97cc53c)
Ezek vajon mitől lehetnek? Lehet, hogy egy migration lemaradt, vagy valami más okozhatja ezt? Az első kép mindenütt előjön, a második csak a create és update függvényeknél.
(Sajnos csak most csatlakoztam be, ezért nem tudom, pontosan mik voltak végrehajtva menet közben)

**Comment by SzBeni2003** [comment]
Ha jól látom, akkor a Prismában nincsen link, de van ownerId, ez okozza az egyik conflictot

**Comment by SzBeni2003** [comment]
![kép](https://github.com/kir-dev/programSCH/assets/58933758/1efde017-f5d0-419e-b374-86c2cc72deca)

**Comment by DannySS123** [comment]
@SzBeni2003 
- "VERY_LOW"-t én nem láttam a priority enumban, oda olyat adj meg ami létezik, célszerű exportálni azt az enum definíciót és azt használni máshol is, pl `Priority.NONE`
- egy migrálást mindenképp megér, azon kívül meg az event enitityben még string van az ownernél user helyett, így az nem lesz kompatibilis, azokat is egységesíteni kell

**Comment by SzBeni2003** [comment]
Ezeket már megoldottuk azóta közösen😅
Annyi volt a megoldás hogy a @prisma/client-ből importáltunk minden saját enumot, és akkor megoldódott a conflict

**Comment by DannySS123** [comment]
Szuper!
